Repository pantheon-systems/terminus, pull requests merged in 2019-02, with the labels that each got.

#1943 Fixes #1941: Test with PHP 7.3.
  .travis.yml
Labels: Ready to Ship

#1944 [AL-1738] - Added plan-name filter to site:list command
  CHANGELOG.md
  src/Collections/Sites.php
  src/Commands/Org/Site/ListCommand.php
  src/Commands/Site/ListCommand.php
  tests/config/behat.yml
  tests/features/site-list.feature
  tests/unit_tests/Collections/SitesTest.php
  tests/unit_tests/Commands/Site/ListCommandTest.php
Labels: Needs Review

#1946 Upstream filters on site:list and org:site:list
  CHANGELOG.md
  src/Collections/Sites.php
  src/Commands/Org/Site/ListCommand.php
  src/Commands/Site/ListCommand.php
  src/Models/Upstream.php
  tests/features/site-list.feature
  tests/unit_tests/Commands/Org/Site/ListCommandTest.php
  tests/unit_tests/Commands/Site/ListCommandTest.php
  tests/unit_tests/Models/UpstreamTest.php
Labels: Ready to Ship

#1948 [AL-1739] - Added checking for uncommitted changes on environments in order to avoid undesired destruction of code
  CHANGELOG.md
  src/Commands/Connection/SetCommand.php
  src/Models/Environment.php
  tests/features/connection-set.feature
  tests/fixtures/connection-set-sftp-uncommitted-changes.yml
  tests/unit_tests/Commands/Connection/SetCommandTest.php
  tests/unit_tests/Models/EnvironmentTest.php
Labels: Ready to Ship

#1928 [AL-1743] - Added PR guidelines to README.md because no guidance is being given presently
  README.md
Labels: Ready to Ship

#1949 [AL-1740] - Added is_owner/Is owner? field to the output of site:team:list in order to clarify which user is the owner
  CHANGELOG.md
  src/Commands/Site/Team/ListCommand.php
  src/Models/SiteUserMembership.php
  tests/features/site-team.feature
  tests/unit_tests/Commands/Site/Team/ListCommandTest.php
  tests/unit_tests/Models/SiteUserMembershipTest.php
Labels: Needs Review

#1952 [AL-1745] - Removed Site::getPHPVersion(), PHP version info from Site::serialize(), site:info because it is misleading and unuseful
  CHANGELOG.md
  src/Commands/Site/InfoCommand.php
  src/Models/Site.php
  tests/features/interactivity.feature
  tests/features/site-info.feature
  tests/unit_tests/Models/SiteTest.php
Labels: Needs Review

#1951 [AL-1746] - Added possible results to upstream:updates:status help text to help users know how to use it
  CHANGELOG.md
  src/Commands/Upstream/Updates/StatusCommand.php
Labels: Needs Review

#1947 AL-1737: Pass callback through to LocalMachineHelper::exec
  CHANGELOG.md
  composer.json
  composer.lock
  src/Commands/Remote/DrushCommand.php
  src/Commands/Remote/SSHBaseCommand.php
  src/Commands/Remote/WPCommand.php
  src/Helpers/LocalMachineHelper.php
  tests/unit_tests/Helpers/LocalMachineHelperTest.php
Labels: Work In Progress
